### ISSUE TITLE
Force close after some days of use

### ISSUE THREAD

**Issue by sfoot13** [TeamNewPipe/NewPipe-nightly#10]
java.lang.IllegalArgumentException: Tried to schedule job for non-existent component: ComponentInfo{org.schabi.newpipe.nightly/org.acra.sender.JobSenderService}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3015)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:263)
	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47)
	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:52)
	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49)
	at org.acra.startup.StartupProcessorExecutor.processReports$lambda$6$lambda$5(StartupProcessorExecutor.kt:60)
	at org.acra.startup.StartupProcessorExecutor.$r8$lambda$LK61ILz0qM6dPNH2J6guur40K2U(StartupProcessorExecutor.kt:0)
	at org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:3025)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:3080)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1249)

**Comment by Stypox** [comment]
This is not the right repository
