### ISSUE TITLE
"ui Error" causes app crash

### ISSUE THREAD

**Issue by Justcallmejake** [TeamNewPipe/NewPipe-nightly#14]
Error seems to appear randomly. Could trigger a minute into app usage or only hours later into usage:

Crashlog:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.extractor.stream.Description.getType()' on a null object reference
	at org.schabi.newpipe.util.text.TextLinkifier.fromDescription(TextLinkifier.java:70)
	at org.schabi.newpipe.util.text.TextEllipsizer.linkifyContentView(TextEllipsizer.java:166)
	at org.schabi.newpipe.util.text.TextEllipsizer.setContent(TextEllipsizer.java:62)
	at org.schabi.newpipe.info_list.holder.CommentInfoItemHolder.updateFromItem(CommentInfoItemHolder.java:127)
	at org.schabi.newpipe.info_list.InfoListAdapter.onBindViewHolder(InfoListAdapter.java:337)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7747)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7847)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6646)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6917)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2106)
	at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2145)
	at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3867)
	at android.view.View.dispatchTouchEvent(View.java:13488)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3216)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2888)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:697)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1879)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3487)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:655)
	at android.view.View.dispatchPointerEvent(View.java:13736)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6116)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5894)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5343)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5396)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5362)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5521)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5370)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5578)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5343)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5396)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5362)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5370)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5343)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8405)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8338)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8291)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8520)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:198)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:187)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8479)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8547)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:986)
	at android.view.Choreographer.doCallbacks(Choreographer.java:764)
	at android.view.Choreographer.doFrame(Choreographer.java:693)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7073)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

```
</details>
<hr>

Easiest way to reproduce the crash so far would be to simply scroll down in comments on a video for multiple refreshes.

Another method is to engage in list scrolling (exception of subscriptions list) whilst app is attempting to load a new video.

**Comment by XiangRongLin** [comment]
Please open the issue in the main repo. This one only builds the most recent version of the application.
