### ISSUE TITLE
UI Error

### ISSUE THREAD

**Issue by ps2string** [TeamNewPipe/NewPipe-nightly#15]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux Android 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.extractor.stream.Description.getType()' on a null object reference
	at org.schabi.newpipe.util.text.TextLinkifier.fromDescription(TextLinkifier.java:70)
	at org.schabi.newpipe.util.text.TextEllipsizer.linkifyContentView(TextEllipsizer.java:166)
	at org.schabi.newpipe.util.text.TextEllipsizer.setContent(TextEllipsizer.java:62)
	at org.schabi.newpipe.info_list.holder.CommentInfoItemHolder.updateFromItem(CommentInfoItemHolder.java:127)
	at org.schabi.newpipe.info_list.InfoListAdapter.onBindViewHolder(InfoListAdapter.java:337)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7747)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7847)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6646)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6917)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2381)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:576)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1816)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1660)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1569)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1816)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1660)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1569)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:325)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:888)
	at android.view.View.layout(View.java:19781)
	at android.view.ViewGroup.layout(ViewGroup.java:6144)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2681)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2384)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1522)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7292)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:721)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

```
</details>
<hr>

So basically the crash log indicates a `java.lang.NullPointerException` error, which means that the app attempted to perform an operation on an object that was null. Specifically, the error occurred when trying to invoke the `getType()` method on an object of type `Description`, which was null at the time.

This kind of error often occurs when there's a programming mistake that leads to an object not being properly initialized or set to null unexpectedly. In this case, it seems that the `Description` object in the `TextLinkifier` class is not being properly handled, resulting in a null reference when trying to access its `getType()` method.

To resolve this issue, the developers of NewPipe will need to review the code related to the `TextLinkifier` class and ensure that objects like `Description` are correctly initialized before accessing their methods. By fixing this bug, they can prevent future instances of this NullPointerException and improve the overall stability of the app.

**Comment by Stypox** [comment]
Errors should not be reported in this repo, but on the main NewPipe repo. Also, that error has already been fixed, and 0.27.0 will soon be released with the fix (testing APKs are available in the main repo)
